name: blogger_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.3.0
  get: ^4.6.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  email_validator: ^2.1.17
  fluttertoast: ^8.2.1
  bcrypt: ^1.1.3
  nanoid: ^1.0.0
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.20

  firebase_storage: ^11.0.16
  image_picker: ^0.8.7
  timeago: ^3.3.0
  loading_animation_widget: ^1.2.0+4
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - assets/fonts/
