// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoALqMZhuaZx5siP6XuCXCrDLx6hMfOKw',
    appId: '1:469516346001:web:407489b70b629f4c21d530',
    messagingSenderId: '469516346001',
    projectId: 'bloggerapp-fc897',
    authDomain: 'bloggerapp-fc897.firebaseapp.com',
    storageBucket: 'bloggerapp-fc897.appspot.com',
    measurementId: 'G-6LS2RSP050',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXSahik5sgVx4DWGOgUrOVWaWGiT4SJAY',
    appId: '1:469516346001:android:428a93fa138bc03921d530',
    messagingSenderId: '469516346001',
    projectId: 'bloggerapp-fc897',
    storageBucket: 'bloggerapp-fc897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6iVtC7t9wBw0n2ky_DPay0-Ge7IS1xA',
    appId: '1:469516346001:ios:adb0c576a41cef3621d530',
    messagingSenderId: '469516346001',
    projectId: 'bloggerapp-fc897',
    storageBucket: 'bloggerapp-fc897.appspot.com',
    iosClientId: '469516346001-6u842tco8jhl878olkag8eoj5p0t2qnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloggerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE6iVtC7t9wBw0n2ky_DPay0-Ge7IS1xA',
    appId: '1:469516346001:ios:adb0c576a41cef3621d530',
    messagingSenderId: '469516346001',
    projectId: 'bloggerapp-fc897',
    storageBucket: 'bloggerapp-fc897.appspot.com',
    iosClientId: '469516346001-6u842tco8jhl878olkag8eoj5p0t2qnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloggerApp',
  );
}
